### ISSUE TITLE
Support to build from string

### ISSUE THREAD

**Issue by alexherbo2** [Val/crun#10]
**Example** – Simple usage:

``` sh
crun eval 'puts ARGV' -- 1 2 3
```

**Example** – Run **crun** with [Kakoune]:

``` kak
$ crun eval %{
  # ---
  # kakoune:
  #   github: alexherbo2/kakoune.cr
  # ---
  require "kakoune"

  ...
} -- %val{session} %val{client}
```

[Kakoune]: https://kakoune.org

**Comment by Val** [comment]
Crystal already has **eval** support : 
```Shell
$ crystal eval 'puts "Hello World"'
Hello World
$ crystal eval 'puts ARGV' -- -- 1 2 3
["1", "2", "3"]
```

Plus I don't know what is your shell but your example will never run on any POSIX shell, even with **bash**  because of the multiline `%{...}` syntax.

**Comment by alexherbo2** [comment]
Crystal has an `eval` command, but the program is not cached.

The second example is a Kakoune command, which has `%{ ... }` strings.

**Comment by Val** [comment]
> Crystal has an `eval` command, but the program is not cached.

How could it be done ? By maintaining a database of all evaluated strings passed with `eval` ? Ugly...
l will not try to provide this feature in **crun** if compiler doesn't support it already, it's far too difficult to handle, sorry.

You should open the issue on Crystal directly.

> The second example is a Kakoune command, which has `%{ ... }` strings.

Ok, so it's look like its your #9 issue
