### ISSUE TITLE
Linux binfmt support fails because of cached compiled file ending with a .cr extension

### ISSUE THREAD

**Issue by aloysius-pgast** [Val/crun#6]
Thanks for this project. 

In current [master](https://github.com/Val/crun/commit/3ebb2ad9e77d40268280f4190e6b85d236e00e55) *build_path* is set [to](https://github.com/Val/crun/blob/master/src/build.cr#L5)

```
@@build_path ||= "#{build_dir}/#{SOURCE_FILENAME}"
```

This means that *build_path* is likely to end with a *.cr* extension. In case *binfmt* support for *.cr* file has been enabled, *crun* will be called again when the cached compiled file is [run](https://github.com/Val/crun/blob/master/src/crun.cr#L34)

```
Process.exec(build_path, ARGS)
```

Adding an extra extension to ensure that cached compiled file does not end with a *.cr* extension should fix the problem 
```
@@build_path ||= "#{build_dir}/#{SOURCE_FILENAME}.crystal"
```

**Comment by Val** [comment]
Good catch !

**Comment by Val** [comment]
@aloysius-pgast : Thank You !
